# Generated by Django 4.0 on 2022-01-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('textarea', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('Operator', 'Оператор'), ('Admin', 'Администратор'), ('Engineer', 'Ведущий инженер')], default='Operator', help_text='Должность', max_length=10),
        ),
    ]
