# Generated by Django 4.0 on 2022-01-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='textarea',
            field=models.TextField(max_length=1000, verbose_name='Поле для отчета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('Operator', 'Оператор'), ('Admin', 'Администратор'), ('Engineer', 'Ведущий инженер')], default='Operator', help_text='Должность', max_length=10, verbose_name='Должность'),
        ),
    ]
