# Generated by Django 4.0 on 2022-02-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_task_closed_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Создана'),
        ),
    ]
