# Generated by Django 4.0 on 2022-01-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_textarea_alter_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('Operator', 'Оператор'), ('Admin', 'Администратор'), ('Engineer', 'Ведущий инженер')], default='Operator', max_length=10, verbose_name='Должность'),
        ),
    ]
