# Generated by Django 4.0 on 2022-01-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_task_note_author_note_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Note', to='notes.user'),
        ),
    ]
