# Generated by Django 4.0 on 2022-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_responsible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tags',
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='note',
            name='task',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите вид задачи', to='notes.Tags'),
        ),
    ]
