# Generated by Django 4.0 on 2022-01-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_noteinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteinstance',
            options={'ordering': ['due_back'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
