# Generated by Django 4.0 on 2022-01-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_noteinstance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='article',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='user',
        ),
    ]
