# Generated by Django 4.0 on 2022-01-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_rename_article_note_title_rename_author_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Выполнить до'),
        ),
    ]
