# Generated by Django 4.0 on 2022-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_noteinstance_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='Введите название задачи', max_length=200, verbose_name='Тег'),
        ),
    ]
