# Generated by Django 4.0 on 2022-01-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_alter_note_user_alter_noteinstance_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
