# Generated by Django 4.0 on 2022-01-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
