# Generated by Django 4.0 on 2022-01-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notes', '0019_alter_users_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersPro',
        ),
        migrations.AddField(
            model_name='note',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.userspro'),
        ),
    ]
