# Generated by Django 4.0 on 2022-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_alter_note_user_alter_note_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(blank=True, choices=[('В работе', 'В работе'), ('Выполнил', 'Выполнил'), ('Отложено', 'Отложено'), ('Открыто', 'Открыто')], default='Открыто', help_text='Статус задачи', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите вид задачи', to='notes.Tags', verbose_name='Теги'),
        ),
    ]
