# Generated by Django 4.0 on 2022-01-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_alter_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='users',
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.userspro', verbose_name='Ответственный'),
        ),
    ]
