# Generated by Django 4.0 on 2022-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_remove_note_users_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите вид задачи', to='notes.Tags', verbose_name='Теги'),
        ),
    ]
