# Generated by Django 4.0 on 2022-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_alter_noteinstance_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspro',
            name='post',
            field=models.CharField(blank=True, choices=[('Operator', 'Оператор'), ('Admin', 'Администратор'), ('Engineer', 'Ведущий инженер')], default='Operator', max_length=10, verbose_name='Должность'),
        ),
    ]
