# Generated by Django 4.0 on 2022-01-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notes', '0030_userspro_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('post', models.CharField(blank=True, choices=[('Operator', 'Оператор'), ('Admin', 'Администратор'), ('Engineer', 'Ведущий инженер')], default='Operator', max_length=10, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.customuser', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='noteinstance',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.customuser'),
        ),
        migrations.DeleteModel(
            name='UsersPro',
        ),
    ]
