# Generated by Django 4.0 on 2022-01-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0034_author_alter_noteinstance_responsible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
