# Generated by Django 4.0 on 2022-01-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0037_alter_noteinstance_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='status',
        ),
        migrations.AddField(
            model_name='noteinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('В работе', 'В работе'), ('Выполнил', 'Выполнил'), ('Отложено', 'Отложено'), ('Открыто', 'Открыто')], default='Открыто', help_text='Статус задачи', max_length=10, verbose_name='Статус'),
        ),
    ]
