# Generated by Django 4.0 on 2022-01-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0038_remove_note_status_noteinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteinstance',
            options={'ordering': ['must_do'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='noteinstance',
            old_name='due_back',
            new_name='must_do',
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите тэг', to='notes.Tags', verbose_name='Теги'),
        ),
    ]
