# Generated by Django 4.0 on 2022-01-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0040_author_user_alter_noteinstance_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
