# Generated by Django 4.0 on 2022-01-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0043_alter_noteinstance_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteinstance',
            options={'ordering': ['must_do'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
