# Generated by Django 4.0 on 2022-01-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0051_alter_note_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
