# Generated by Django 4.0 on 2022-01-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0052_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterModelOptions(
            name='noteinstance',
            options={'ordering': ['must_do'], 'permissions': (('can_mark_returned', 'Что-то должно тут быть'),), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
