# Generated by Django 4.0 on 2022-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0053_alter_note_options_alter_noteinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Выполнить до'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите тег', to='notes.Tags', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='noteinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('Выполнил', 'Выполнил'), ('Открыто', 'Открыто')], default='Открыто', help_text='Статус задачи', max_length=10, verbose_name='Статус'),
        ),
    ]
