# Generated by Django 4.0 on 2022-02-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0054_alter_note_date_alter_note_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AlterField(
            model_name='noteinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('В работе', 'В работе'), ('Выполнил', 'Выполнил'), ('Отложено', 'Отложено'), ('Открыто', 'Открыто')], default='Открыто', help_text='Статус задачи', max_length=10, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
